### ISSUE TITLE
volumio playback status not considered

### ISSUE THREAD

**Issue by jo-me** [timolex/Radiodawg#2]
The current playback status is not considered. 
If it is "stop" before internet dropout it would be resumed by the script, right?

So `"status": "play"` should be checked in is_streaming_webradio(),
e.g. `volumio status | grep '"status": "play"'`

```
volumio@volumio:~$ volumio status
{
  "status": "stop",
  "position": 0,
  "title": "egofmbw.mp3",
   ...
  "trackType": "webradio",

```

**Comment by timolex** [comment]
Yes correct, this is a behavior known & expected by me, I've now introduced a check & constant w.r.t. playback state consideration in the linked PR. The default setting is now pre-dropout playback state consideration, but die-hard webradio junkies like me will prefer the "aggressive" playback policy and set CONSIDER_PLAYBACK_STATUS=False :)
